services:

  postgres:
    image: postgres:18
    container_name: sermocino-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: sermocino-auth
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PORT}:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      JWT_SECRET_KEY: "${JWT_SECRET}"
      COOKIE_SECRET: "920a25b214bf89e6e3ad3faa5d1fdd7619a1e9dc97f4cadfbe3cbd284ab18db5"
      NODE_ENV: "development"
    restart: unless-stopped

volumes:
  pgdata:
