packages:
  - services/**
  - clients/**
  - packages/*

onlyBuiltDependencies:
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - msgpackr-extract
  - msw
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
